######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 26 11:15:12 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += DEBUG

system(cd .. && perl mindspace-types.pl)

# Input
HEADERS += ../MindSpace.h
SOURCES += main.cpp ../MindSpace.cpp
