#include "MindSpace.h"

#include <QUuid>
#include <QStringList>

namespace MindSpace
{
 
/* Our predefined types */
#define DefineNodeType(name, uuid) \
	static MNodeType MNodeType_##name ( #name, uuid); \
	const MNodeType & MNodeType:: name() { return MNodeType_##name; }

#define DefineLinkType(name, uuid) \
	static MLinkType MLinkType_##name ( #name, uuid); \
	const MLinkType & MLinkType:: name() { return MLinkType_##name; }

#define DefineLinkTypeList(name, uuid) \
	static MLinkType MLinkType_##name ( #name, uuid, true); \
	const MLinkType & MLinkType:: name() { return MLinkType_##name; }

// Generated by mindspace-types.pl from MindSpace.types
#include "mindspace-types.definitions"


/** Destroy the MSpace **/
MSpace::~MSpace() {}

MSpace *MSpace::s_activeSpace = 0;

MNode *MSpace::uuidToNode(const QString& uuid)
{
	/// TODO
	return 0;
}

MLink *MSpace::uuidToLink(const QString& uuid)
{
	/// TODO
	return 0;
}



}; /* namespace MindSpace */
