######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 27 16:44:45 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += AnnNode.h
SOURCES += AnnNode.cpp main.cpp
